
package org.building.pm.wclient.JXWCJG;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_JXWCJG_Out_SynService", targetNamespace = "http://www.anshanmining.com/EAM_PM/", wsdlLocation = "file:/E:/\u8bbe\u5907/\u63a5\u53e3/SI_JXWCJG_Out_Syn_PM0014.wsdl")
public class SIJXWCJGOutSynService
    extends Service
{

    private final static URL SIJXWCJGOUTSYNSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIJXWCJGOUTSYNSERVICE_EXCEPTION;
    private final static QName SIJXWCJGOUTSYNSERVICE_QNAME = new QName("http://www.anshanmining.com/EAM_PM/", "SI_JXWCJG_Out_SynService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/E:/\u8bbe\u5907/\u63a5\u53e3/SI_JXWCJG_Out_Syn_PM0014.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIJXWCJGOUTSYNSERVICE_WSDL_LOCATION = url;
        SIJXWCJGOUTSYNSERVICE_EXCEPTION = e;
    }

    public SIJXWCJGOutSynService() {
        super(__getWsdlLocation(), SIJXWCJGOUTSYNSERVICE_QNAME);
    }

    public SIJXWCJGOutSynService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIJXWCJGOUTSYNSERVICE_QNAME, features);
    }

    public SIJXWCJGOutSynService(URL wsdlLocation) {
        super(wsdlLocation, SIJXWCJGOUTSYNSERVICE_QNAME);
    }

    public SIJXWCJGOutSynService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIJXWCJGOUTSYNSERVICE_QNAME, features);
    }

    public SIJXWCJGOutSynService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIJXWCJGOutSynService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIJXWCJGOutSyn
     */
    @WebEndpoint(name = "SI_JXWCJG_Out_SynPort")
    public SIJXWCJGOutSyn getSIJXWCJGOutSynPort() {
        return super.getPort(new QName("http://www.anshanmining.com/EAM_PM/", "SI_JXWCJG_Out_SynPort"), SIJXWCJGOutSyn.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIJXWCJGOutSyn
     */
    @WebEndpoint(name = "SI_JXWCJG_Out_SynPort")
    public SIJXWCJGOutSyn getSIJXWCJGOutSynPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.anshanmining.com/EAM_PM/", "SI_JXWCJG_Out_SynPort"), SIJXWCJGOutSyn.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIJXWCJGOUTSYNSERVICE_EXCEPTION!= null) {
            throw SIJXWCJGOUTSYNSERVICE_EXCEPTION;
        }
        return SIJXWCJGOUTSYNSERVICE_WSDL_LOCATION;
    }

}
