
package org.building.pm.wclient.JXWCJG;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_JXWCJG_Out_Syn", targetNamespace = "http://www.anshanmining.com/EAM_PM/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIJXWCJGOutSyn {


    /**
     * 
     * @param mtJXWCJG
     * @return
     *     returns com.anshanmining.eam_pm.DTJXWCJGRet
     */
    @WebMethod(operationName = "SI_JXWCJG", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_JXWCJGRet", targetNamespace = "http://www.anshanmining.com/EAM_PM/", partName = "MT_JXWCJGRet")
    public DTJXWCJGRet siJXWCJG(
            @WebParam(name = "MT_JXWCJG", targetNamespace = "http://www.anshanmining.com/EAM_PM/", partName = "MT_JXWCJG")
                    DTJXWCJG mtJXWCJG);

}
